"""Vercel entrypoint for the public demo at kira-demo.vercel.app.

The demo runs the real application — the same FastAPI routes, the same
SQLAlchemy queries, the same filtering and parking matching. What differs is the
data underneath it: `demo/demo.db` holds invented listings generated by
`demo/generate_demo_db.py`. Nothing here was scraped, and the demo never
scrapes: `RS_DEMO=1` closes the scrape endpoint and the image proxy, the two
routes that would reach out to a third-party site.

Serverless filesystem notes: the deployment bundle is read-only and only `/tmp`
is writable, so the bundled database is copied there on cold start. SQLite then
has somewhere to put its journal, and the copy is discarded with the instance.
"""
from __future__ import annotations

import os
import shutil
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

BUNDLED_DB = ROOT / "demo" / "demo.db"
RUNTIME_DB = Path("/tmp/kira-demo.db")


def _freshen(db_path: Path) -> None:
    """Roll every timestamp forward so the demo does not go stale.

    The listings are generated once and committed, so without this they would
    age out of the `listing_active_days` window and the demo would empty itself
    a few days after deployment. Shifting the whole table by the same interval
    keeps the relative spacing — some listings still read as posted today,
    others as posted a week ago.
    """
    with sqlite3.connect(db_path) as con:
        row = con.execute(
            "SELECT CAST(strftime('%s', 'now') AS INTEGER)"
            " - CAST(strftime('%s', MAX(last_seen_at)) AS INTEGER) FROM listings"
        ).fetchone()
        shift = int(row[0] or 0)
        if shift <= 0:
            return
        offset = f"+{shift} seconds"
        tables = {
            "listings": ("posted_at", "first_seen_at", "last_seen_at"),
            "parking_spots": ("first_seen_at", "last_seen_at"),
            "scrape_runs": ("started_at", "finished_at"),
        }
        for table, columns in tables.items():
            assignments = ", ".join(f"{c} = datetime({c}, ?)" for c in columns)
            con.execute(f"UPDATE {table} SET {assignments}", (offset,) * len(columns))
        con.commit()


if not RUNTIME_DB.exists():
    shutil.copyfile(BUNDLED_DB, RUNTIME_DB)
    _freshen(RUNTIME_DB)

os.environ.setdefault("RS_DATABASE_URL", f"sqlite:///{RUNTIME_DB.as_posix()}")
os.environ.setdefault("RS_DEMO", "1")

from app.main import app  # noqa: E402  (must follow the env setup above)

__all__ = ["app"]
